name = "vevsdesign-contact"
main = "worker.mjs"
compatibility_date = "2026-05-15"

[observability.logs]
enabled = true

[vars]
ALLOWED_ORIGIN = "https://vevsdesign.sk"
CONTACT_TO_EMAIL = "vevsdesignn@gmail.com"
